### ISSUE TITLE
Dev mode enhancment

### ISSUE THREAD

**Issue by Dimitreee** [8iq/nodejs-hackathon-boilerplate-starter-kit#27]
Nowadays we got a problem we should to deal with:
When i need to apply my updates on backend i should rebuild my project by manually typing simple cli command, like `yarn dev`, or smthng. It would be nice if i used to do nothing when i update my backend source code. Packages like nodemon can solve this propblem.

So at the point of this issue we should improve `dev mode` and add auto-rebuild when changes accepted.

**Comment by yamuru** [comment]
I am not deeply into this template, but couldn't you use a nodemon?
nodemon either could be used in "nodemon ./bin/run-multiple-apps", or "nodemon --exec keystone dev" inside a particular project.

**Comment by Dimitreee** [comment]
@yamuru yes, we do. Can you create pr with your solution?
